version: "2"

services:
  frontend:
    build: ./frontend
    ports:
      - 8080:8080
    volumes:
      - ./frontend:/data
    environment:
      - API_URL=http://localhost:8081/

  backend:
    build: ./backend
    ports:
      - 8081:8081
    volumes:
      - ./backend:/data
    depends_on: 
      - server-database
    environment:
      - DATABASE_URL=server-database:27017
    
  server-database:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db

    